# Generated by Django 4.2.21 on 2026-03-03 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="date",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="department",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="description",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="user",
        ),
    ]
