# Generated by Django 4.2.21 on 2026-03-27 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0005_alter_customuser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
