# Generated by Django 4.2.21 on 2026-03-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0006_remove_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
