# Generated by Django 4.2.21 on 2026-03-31 14:01

from django.db import migrations
from django.db import migrations

def create_admin_user(apps, schema_editor):
    CustomUser = apps.get_model("expenses", "CustomUser")
    if not CustomUser.objects.filter(email="admin@gmail.com").exists():
        user = CustomUser(
            email="admin@gmail.com",
            username="admin@gmail.com",
            fullname="Ruvarashe Shoko",
            role="Admin",
            is_staff=True,
            is_superuser=True,
            is_active=True,
        )
        user.set_password("1234")  # hashes the password properly
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0007_previous_migration"),  # replace with your latest migration
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]



class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0007_customuser_username"),
    ]

    operations = [
         migrations.RunPython(create_admin_user),
    ]
