# Generated by Django 4.2.21 on 2026-03-31 14:01

from django.db import migrations

def create_admin_user(apps, schema_editor):
    CustomUser = apps.get_model("expenses", "CustomUser")
    if not CustomUser.objects.filter(email="admin@gmail.com").exists():
        CustomUser.objects.create_superuser(
            email="admin@gmail.com",
            password="1234",
            fullname="Ruvarashe Shoko",
            role="Admin"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0007_customuser_username"),
    ]

    operations = [
         migrations.RunPython(create_admin_user),
    ]
