# Generated by Django 4.2.21 on 2026-03-31 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0008_create_admin_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="expense",
        ),
    ]
