# Generated by Django 4.2.21 on 2025-10-02 12:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="inventory",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("product_id", models.CharField(max_length=250)),
                ("product_name", models.CharField(max_length=250)),
                ("units", models.CharField(max_length=250)),
                ("total_quantity", models.IntegerField()),
            ],
            options={
                "db_table": "product_stock2",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("budget_id", models.CharField(max_length=255)),
                ("month", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=60)),
            ],
        ),
        migrations.CreateModel(
            name="expense_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="manufactured_products",
            fields=[
                (
                    "m_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("quantity", models.IntegerField()),
                ("description", models.TextField()),
                ("total", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="our_product",
            fields=[
                (
                    "product_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("product_name", models.CharField(max_length=1000)),
                ("units", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="product_variant",
            fields=[
                (
                    "product_var_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("unit_size", models.FloatField()),
                ("unit", models.CharField(max_length=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot.our_product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="user_stock_record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("product", models.CharField(max_length=255)),
                ("unit_size", models.FloatField()),
                ("unit", models.CharField(max_length=255)),
                ("allocated", models.FloatField()),
                ("sold", models.FloatField()),
                ("remaining", models.FloatField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("full_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="stock",
            fields=[
                (
                    "stock_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                (
                    "col_allo_stat",
                    models.CharField(
                        choices=[
                            ("ALLOCATED", "Allocated"),
                            ("NOT_ALLOCATED", "Not Allocated"),
                        ],
                        default="NOT_ALLOCATED",
                        max_length=30,
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot.manufactured_products",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.TextField()),
                ("quantity", models.IntegerField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=60)),
                ("status", models.CharField(max_length=20)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=60)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot.product_variant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chatbot.users"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="packing",
            fields=[
                (
                    "pack_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("quantity", models.FloatField()),
                ("unit_size", models.FloatField()),
                ("unit", models.CharField(max_length=20)),
                ("date", models.DateField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot.product_variant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="manufactured_products",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chatbot.our_product"
            ),
        ),
        migrations.CreateModel(
            name="expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expense_id", models.CharField(max_length=255)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=60)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chatbot.budget"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot.expense_category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="credit_payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=60)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chatbot.users"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cashier_report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RECEIVE", "Received from Seller"),
                            ("RELEASE", "Released"),
                        ],
                        default="RECEIVE",
                        max_length=255,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=65)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chatbot.users"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("quantity", models.IntegerField()),
                ("unit_size", models.FloatField()),
                ("units", models.CharField(max_length=300)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=60)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=60)),
                (
                    "pack_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot.packing",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chatbot.users"
                    ),
                ),
            ],
        ),
    ]
