# Generated by Django 4.2.21 on 2025-10-02 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allocation",
            name="pack_id",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="cashier_report",
            name="source",
        ),
        migrations.RemoveField(
            model_name="credit_payment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="budget",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="category",
        ),
        migrations.RemoveField(
            model_name="manufactured_products",
            name="product",
        ),
        migrations.RemoveField(
            model_name="packing",
            name="product",
        ),
        migrations.RemoveField(
            model_name="product_variant",
            name="product",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="product",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="user",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="product_id",
        ),
        migrations.DeleteModel(
            name="user_stock_record",
        ),
        migrations.DeleteModel(
            name="inventory",
        ),
        migrations.DeleteModel(
            name="allocation",
        ),
        migrations.DeleteModel(
            name="budget",
        ),
        migrations.DeleteModel(
            name="cashier_report",
        ),
        migrations.DeleteModel(
            name="credit_payment",
        ),
        migrations.DeleteModel(
            name="expense",
        ),
        migrations.DeleteModel(
            name="expense_category",
        ),
        migrations.DeleteModel(
            name="manufactured_products",
        ),
        migrations.DeleteModel(
            name="our_product",
        ),
        migrations.DeleteModel(
            name="packing",
        ),
        migrations.DeleteModel(
            name="product_variant",
        ),
        migrations.DeleteModel(
            name="sales",
        ),
        migrations.DeleteModel(
            name="stock",
        ),
        migrations.DeleteModel(
            name="users",
        ),
    ]
